---
name: Bug report
description: Create a report to help us improve MacVim.
labels: [bug]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting issues of MacVim!

        If you want to report a security issue, instead of reporting it here
        you can alternatively disclose it on
        [huntr.dev](https://huntr.dev/bounties/disclose/?utm_campaign=macvim-dev%2Fmacvim&utm_medium=social&utm_source=github&target=https%3A%2F%2Fgithub.com%2Fmacvim-dev%2Fmacvim).
        They have rewards in the form of money, swag and CVEs.
        
        To make it easier for us to help you please enter detailed information below.
  - type: textarea
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. 
        2. 
        3. 
        4. 
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behaviour
      placeholder: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: input
    attributes:
      label: Version of Vim and architecture
      description: >
        Including patch level, use ":version" to see it [e.g. 8.2.1234, GUI, arm64]
    validations:
      required: true
  - type: textarea
    attributes:
      label: Environment
      description: >
        OS and architecture [e.g. Big Sur, arm64], terminal [e.g. Apple Terminal/iTerm], value of $TERM, shell [e.g. zsh 5.8]; anything that might matter
      placeholder: |
        Operating system:
        Terminal:
        Value of $TERM:
        Shell:
    validations:
      required: true
  - type: input
    attributes:
      label: How MacVim was installed
      description: >
        MacVim has been downloaded from GitHub, installed via Homebrew, MacPorts or builed from git
  - type: textarea
    attributes:
      label: Logs and stack traces
      placeholder: Insert log or other text here (if necessary)
      render: shell
  - type: input
    attributes:
      label: Vim configuration where issue is reproducable
      description: 'e.g. link to your vimrc configuration: url to file/gist/repo..'
  - type: checkboxes
    attributes:
      label: Issue has been tested with given configuration
      description: This will help us to narrow down the problem more quickly
      options:
        - label: by running MacVim.app from GUI macOS interface
        - label: by running vim/gvim/etc installed by MacVim
        - label: by running other versions of vim (e.g. /usr/bin/vim)
  - type: checkboxes
    attributes:
      label: Issue has been tested with no configuration
      description: This will help us to narrow down the problem more quickly
      options:
        - label: by running `mvim --clean` (or `gvim`, supplied by MacVim distribution)
        - label: by running `vim --clean` (in terminal, supplied by MacVim distribution)
        - label: by running `vim --clean` (in terminal, other suppliers, e.g. /usr/bin/vim)
  - type: checkboxes
    attributes:
      label: Other conditions
      description: This will help us to narrow down the problem more quickly
      options:
        - label: The both Homebrew packages "vim" and "macvim" are installed
